apiVersion: v1
kind: Service
metadata:
  name: sample-app-image-service
spec:
  selector:
    app: sample-app-image
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer   # Change to LoadBalancer if needed
