apiVersion: v1
kind: Service
metadata:
  name: sample-app-image-service
spec:
  type: NodePort
  selector:
    app: sample-app-image
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010

