name: CI-Maven-Project-Workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          distribution: 'microsoft'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Copy JAR from target to custom directory staging
        run: mkdir staging && cp target/*.jar staging
      - name: Upload a Build Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: staging


