name: ReusableWorkflow
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run usable workflow
        run: echo 'This is a usable workflow step'
