name: Self-Hosted Agent Workflow

on:
  workflow_dispatch:
    inputs:
      TARGET_ENVIRONMENT:
        type: environment
        default: dev
        description: 'Select the target environment for deployment'

jobs:
  build:
    runs-on: [self-hosted, Windows, X64, gpu, yogendra-vm1-host]
    environment: ${{ inputs.TARGET_ENVIRONMENT }}
    steps:
      - name: Install Java (JDK 17)
        shell: powershell
        run: |
          $jdkUrl = "https://download.oracle.com/java/17/archive/jdk-17.0.12_windows-x64_bin.zip"
          $jdkZip = "$env:TEMP\jdk.zip"
          Invoke-WebRequest -Uri $jdkUrl -OutFile $jdkZip
          Expand-Archive -Path $jdkZip -DestinationPath "C:\Java" -Force
          $jdkPath = Get-ChildItem "C:\Java" | Where-Object { $_.PSIsContainer } | Select-Object -First 1 -ExpandProperty FullName
          [System.Environment]::SetEnvironmentVariable("JAVA_HOME", $jdkPath, "Machine")
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";" + "$jdkPath\bin", "Machine")
          java -version

      - name: Install Maven
        shell: powershell
        run: |
          $mavenUrl = "https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip"
          $mavenZip = "$env:TEMP\maven.zip"
          Invoke-WebRequest -Uri $mavenUrl -OutFile $mavenZip
          Expand-Archive -Path $mavenZip -DestinationPath "C:\Maven" -Force
          $mavenPath = Get-ChildItem "C:\Maven" | Where-Object { $_.PSIsContainer } | Select-Object -First 1 -ExpandProperty FullName
          [System.Environment]::SetEnvironmentVariable("M2_HOME", $mavenPath, "Machine")
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";" + "$mavenPath\bin", "Machine")
          mvn -version

      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Build with Maven
        shell: powershell
        run: mvn --batch-mode --update-snapshots verify

      - name: Copy JAR from target to custom staging directory
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path staging -Force | Out-Null
          Copy-Item "target\*.jar" staging\

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: staging
